### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Argmaster** [aio-libs/sort-all#41]
Is this project dead?

**Comment by asvetlov** [comment]
Thanks for the question.

The project was functional without any touch for years because of its simplicity.

Now 1.3.0 version was released to support `--check` and `--no-error-on-fix` options. 
CI was updated to be green again by using fresh tool versions.
That said, I don't expect many changes or feature requests in the future. 
Sorting `__all__` is a trivial thing; it doesn't left a space for improvements.
